Repository kubernetes-sigs/apiserver-runtime, pull requests merged in 2020-09, with the labels that each got.

#2 switch branches for CI
  .github/workflows/go.yml
Labels: cncf-cla: yes

#5 update README.md with docs links
  README.md
  pkg/builder/example_test.go
Labels: cncf-cla: yes, size/S

#6 fix nil error
  .gitignore
  internal/sample-apiserver/pkg/cmd/server/start.go
Labels: cncf-cla: yes

#8 Make warning louder
  README.md
Labels: cncf-cla: yes

#9 Refactor: Split a custom storage file
  sample/pkg/apis/sample/v1alpha1/fortune.go
  sample/pkg/apis/sample/v1alpha1/fortune_storage.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#11 Don't generate clients by default
  sample/Makefile
  tools/apiserver-runtime-gen/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#13 More docs
  pkg/builder/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#14 Simplifies status subresource extension interface
  go.mod
  go.sum
  internal/sample-apiserver/pkg/cmd/server/ext.go
  internal/sample-apiserver/pkg/cmd/server/start.go
  internal/sample-apiserver/pkg/generated/openapi/zz_generated.openapi.go
  pkg/builder/builder.go
  pkg/builder/resource/types.go
  pkg/builder/resource/util/deepcopy.go
  pkg/builder/resource/util/deepcopy_test.go
  pkg/builder/resource/util/doc.go
  pkg/builder/rest/rest.go
  pkg/builder/rest/status.go
  pkg/builder/rest/strategy.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#17 Rebasing apiserver-builder onto runtime
  go.mod
  internal/sample-apiserver/main.go
  internal/sample-apiserver/pkg/apiserver/apiserver.go
  internal/sample-apiserver/pkg/apiserver/ext.go
  internal/sample-apiserver/pkg/cmd/server/ext.go
  internal/sample-apiserver/pkg/cmd/server/start.go
  pkg/builder/builder.go
  pkg/builder/resource/resourcerest/interface.go
  pkg/builder/resource/types.go
  pkg/builder/rest/rest.go
  pkg/builder/rest/status.go
  pkg/builder/rest/strategy.go
  sample/pkg/apis/sample/v1alpha1/fischers.go
  sample/pkg/apis/sample/v1alpha1/flunders.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#18 OWNER file fix
  OWNERS
Labels: cncf-cla: yes, size/S

#20 Feat: Providing storage functions for mysql storage
  go.mod
  go.sum
  pkg/experimental/storage/mysql/kine.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#19 Breakdown builders into separated files
  internal/example/cmd/main.go
  pkg/builder/builder.go
  pkg/builder/builder_admission.go
  pkg/builder/builder_auth.go
  pkg/builder/builder_general.go
  pkg/builder/builder_misc.go
  pkg/builder/builder_resource.go
  pkg/builder/rest/rest.go
  pkg/builder/storage_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
