Repository kubernetes-sigs/apiserver-runtime, pull requests merged in 2022-11, with the labels that each got.

#82 Bump golang to 1.18.2 (including test infra)
  .github/workflows/go.yml
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#81 Feat: upgrade go version and k8s api version
  .github/workflows/go.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  doc.go
  go.mod
  go.sum
  internal/example/handler/handler.go
  pkg/builder/builder_misc.go
  pkg/builder/doc.go
  pkg/builder/rest/provider.go
  pkg/builder/storage_provider.go
  pkg/experimental/storage/filepath/jsonfile.go
  pkg/experimental/storage/filepath/jsonfile_rest.go
  pkg/experimental/storage/mysql/kine.go
  sample/pkg/apis/sample/v1alpha1/fortune.go
  sample/pkg/generated/clientset/versioned/clientset.go
  sample/pkg/generated/clientset/versioned/fake/register.go
  sample/pkg/generated/clientset/versioned/scheme/register.go
  sample/pkg/generated/clientset/versioned/typed/sample/v1alpha1/fake/fake_fischer.go
  sample/pkg/generated/clientset/versioned/typed/sample/v1alpha1/fake/fake_flunder.go
  sample/pkg/generated/clientset/versioned/typed/sample/v1alpha1/fake/fake_fortune.go
  sample/pkg/generated/clientset/versioned/typed/sample/v1alpha1/sample_client.go
  sample/pkg/generated/openapi/zz_generated.openapi.go
  tools/apiserver-runtime-gen/main.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#83 stick klog to v2 version, drop klog v1 reference
  go.mod
  go.sum
  pkg/builder/builder_auth.go
  pkg/builder/builder_resource.go
  sample/cmd/apiserver/main.go
Labels: size/XS, cncf-cla: yes, approved, lgtm
